import { CSSProperties } from "react";
import { colors } from "../../assets/colors";

const styles: { [key: string]: CSSProperties } = {
  header: {
    height: "78px",
    width: "100%",
  },
  borderBottom: {
    display: "flex",
    width: "100%",
    height: "7px",
    background: `linear-gradient(to right, ${colors.white} 0%, ${colors.darkBlue} 50%, ${colors.white} 100%)`,
  },
  mainContent: {
    display: "grid",
    height: "71px",
    width: "100%",
    gridTemplateColumns: "1.5fr 1fr 1.5fr",
  },
  navButtons: {
    display: "flex",
    alignItems: "center",
    paddingLeft: "50px",
  },
  logo: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  logoImage: {
    height: "50px",
    cursor: "pointer",
  },
  navButton: {
    color: colors.darkBlue,
    fontSize: "24px",
    fontWeight: "semibold",
    paddingRight: "20px",
    cursor: "pointer",
    fontFamily: "Montserrat, sans-serif",
    textTransform: "uppercase",
  },
  navButtonPicked: {
    color: colors.darkBlue,
    fontSize: "24px",
    fontWeight: "semibold",
    marginRight: "20px",
    cursor: "pointer",
    fontFamily: "Montserrat, sans-serif",
    textTransform: "uppercase",
    borderBottom: `1px solid ${colors.darkBlue}`,
  },
  socialsAndLanguage: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    paddingRight: "50px",
  },
  socials: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  socialIcon: {
    height: "30px",
    width: "30px",
    margin: "10px",
    cursor: "pointer",
  },
  language: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  languageText: {
    color: colors.darkBlue,
    fontSize: "24px",
    fontWeight: "semibold",
    paddingRight: "10px",
    cursor: "pointer",
    fontFamily: "Montserrat, sans-serif",
  },
  mainContentMobile: {
    display: "flex",
    justifyContent: "space-between",
    height: "71px",
    width: "100%",
  },
  simpleLogo: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    paddingLeft: "50px",
  },
  simpleLogoImage: {
    height: "50px",
    cursor: "pointer",
  },
  burgerMenu: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    paddingRight: "50px",
  },
  burgerIcon: {
    cursor: "pointer",
    transition: "transform 0.3s ease-in-out",
  },
  mobileMenu: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    backgroundColor: colors.offWhite,
    position: "absolute",
    top: "78px", // Below the header
    left: 0,
    right: 0,
    padding: "10px 0",
    zIndex: 1000,
    boxShadow: "0 4px 8px rgba(0, 0, 0, 0.25)",
  },
  mobileSubMenu: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "80%",
    margin: "20px 0",
  },
  mobileLanguageSubMenu: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    width: "80%",
    margin: "20px 0",
  },
  mobileNavButtonPicked: {
    color: colors.darkBlue,
    fontSize: "24px",
    fontWeight: "semibold",
    cursor: "pointer",
    fontFamily: "Montserrat, sans-serif",
    textTransform: "uppercase",
    borderBottom: `1px solid ${colors.darkBlue}`,
    marginTop: "10px",
  },
  mobileNavButton: {
    color: colors.darkBlue,
    fontSize: "24px",
    fontWeight: "semibold",
    cursor: "pointer",
    fontFamily: "Montserrat, sans-serif",
    textTransform: "uppercase",
    marginTop: "10px",
  },
  mobileSubNavButton: {
    color: colors.darkBlue,
    fontSize: "20px",
    fontWeight: "semibold",
    cursor: "pointer",
    fontFamily: "Montserrat, sans-serif",
    textTransform: "uppercase",
  },
  mobileSubNavButtonPicked: {
    color: colors.darkBlue,
    fontSize: "20px",
    fontWeight: "semibold",
    cursor: "pointer",
    fontFamily: "Montserrat, sans-serif",
    textTransform: "uppercase",
    borderBottom: `1px solid ${colors.darkBlue}`,
    marginTop: "10px",
  },
  mobileSocials: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginTop: "10px",
  },
  languageSelector: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    backgroundColor: colors.offWhite,
    position: "absolute",
    top: "78px", // Below the header
    left: "80%",
    right: 0,
    padding: "10px 0",
    zIndex: 1000,
    boxShadow: "0 4px 8px rgba(0, 0, 0, 0.25)",
  },
  languageSelectorContent: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "10px",
  },
  languageSelectorButton: {
    color: colors.darkBlue,
    fontSize: "24px",
    fontWeight: "semibold",
    cursor: "pointer",
    fontFamily: "Montserrat, sans-serif",
    textTransform: "uppercase",
    margin: "10px",
  },
  languageSelectorButtonPicked: {
    color: colors.darkBlue,
    fontSize: "24px",
    fontWeight: "semibold",
    cursor: "pointer",
    fontFamily: "Montserrat, sans-serif",
    textTransform: "uppercase",
    borderBottom: `1px solid ${colors.darkBlue}`,
    margin: "10px",
  },
  floatingLogo: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    transition: "transform 0.3s ease, width 0.3s ease, height 0.3s ease",
    width: "120px",
    height: "120px",
  },
  floatingLogoShrunk: {
    transform: "translate(-50%, -50%) scale(0.7)",
    width: "80px",
    height: "80px",
  },
};

export default styles;
